// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class LanguageInfo {
    protected java.lang.String name;
    protected java.lang.String[] suffixes;
    protected int defMinMatchLen;
    
    public LanguageInfo() {
    }
    
    public LanguageInfo(java.lang.String name, java.lang.String[] suffixes, int defMinMatchLen) {
        this.name = name;
        this.suffixes = suffixes;
        this.defMinMatchLen = defMinMatchLen;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String[] getSuffixes() {
        return suffixes;
    }
    
    public void setSuffixes(java.lang.String[] suffixes) {
        this.suffixes = suffixes;
    }
    
    public int getDefMinMatchLen() {
        return defMinMatchLen;
    }
    
    public void setDefMinMatchLen(int defMinMatchLen) {
        this.defMinMatchLen = defMinMatchLen;
    }
}
