// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class MailTemplateArray {
    protected jplagTutorial.jplagClient.MailTemplate[] items;
    
    public MailTemplateArray() {
    }
    
    public MailTemplateArray(jplagTutorial.jplagClient.MailTemplate[] items) {
        this.items = items;
    }
    
    public jplagTutorial.jplagClient.MailTemplate[] getItems() {
        return items;
    }
    
    public void setItems(jplagTutorial.jplagClient.MailTemplate[] items) {
        this.items = items;
    }
}
