// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class RequestData {
    protected java.lang.String validateTime;
    protected java.lang.String username;
    protected java.lang.String password;
    protected java.lang.String realName;
    protected java.lang.String email;
    protected java.lang.String emailSecond;
    protected java.lang.String homepage;
    protected java.lang.String reason;
    protected java.lang.String notes;
    
    public RequestData() {
    }
    
    public RequestData(java.lang.String validateTime, java.lang.String username, java.lang.String password, java.lang.String realName, java.lang.String email, java.lang.String emailSecond, java.lang.String homepage, java.lang.String reason, java.lang.String notes) {
        this.validateTime = validateTime;
        this.username = username;
        this.password = password;
        this.realName = realName;
        this.email = email;
        this.emailSecond = emailSecond;
        this.homepage = homepage;
        this.reason = reason;
        this.notes = notes;
    }
    
    public java.lang.String getValidateTime() {
        return validateTime;
    }
    
    public void setValidateTime(java.lang.String validateTime) {
        this.validateTime = validateTime;
    }
    
    public java.lang.String getUsername() {
        return username;
    }
    
    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getRealName() {
        return realName;
    }
    
    public void setRealName(java.lang.String realName) {
        this.realName = realName;
    }
    
    public java.lang.String getEmail() {
        return email;
    }
    
    public void setEmail(java.lang.String email) {
        this.email = email;
    }
    
    public java.lang.String getEmailSecond() {
        return emailSecond;
    }
    
    public void setEmailSecond(java.lang.String emailSecond) {
        this.emailSecond = emailSecond;
    }
    
    public java.lang.String getHomepage() {
        return homepage;
    }
    
    public void setHomepage(java.lang.String homepage) {
        this.homepage = homepage;
    }
    
    public java.lang.String getReason() {
        return reason;
    }
    
    public void setReason(java.lang.String reason) {
        this.reason = reason;
    }
    
    public java.lang.String getNotes() {
        return notes;
    }
    
    public void setNotes(java.lang.String notes) {
        this.notes = notes;
    }
}
