// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class RequestDataArray {
    protected jplagTutorial.jplagClient.RequestData[] items;
    
    public RequestDataArray() {
    }
    
    public RequestDataArray(jplagTutorial.jplagClient.RequestData[] items) {
        this.items = items;
    }
    
    public jplagTutorial.jplagClient.RequestData[] getItems() {
        return items;
    }
    
    public void setItems(jplagTutorial.jplagClient.RequestData[] items) {
        this.items = items;
    }
}
