// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class SetMailTemplateParams {
    protected int type;
    protected jplagTutorial.jplagClient.MailTemplate template;
    
    public SetMailTemplateParams() {
    }
    
    public SetMailTemplateParams(int type, jplagTutorial.jplagClient.MailTemplate template) {
        this.type = type;
        this.template = template;
    }
    
    public int getType() {
        return type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    
    public jplagTutorial.jplagClient.MailTemplate getTemplate() {
        return template;
    }
    
    public void setTemplate(jplagTutorial.jplagClient.MailTemplate template) {
        this.template = template;
    }
}
