// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class SetUserDataParams {
    protected jplagTutorial.jplagClient.UserData userdata;
    protected java.lang.String oldUsername;
    
    public SetUserDataParams() {
    }
    
    public SetUserDataParams(jplagTutorial.jplagClient.UserData userdata, java.lang.String oldUsername) {
        this.userdata = userdata;
        this.oldUsername = oldUsername;
    }
    
    public jplagTutorial.jplagClient.UserData getUserdata() {
        return userdata;
    }
    
    public void setUserdata(jplagTutorial.jplagClient.UserData userdata) {
        this.userdata = userdata;
    }
    
    public java.lang.String getOldUsername() {
        return oldUsername;
    }
    
    public void setOldUsername(java.lang.String oldUsername) {
        this.oldUsername = oldUsername;
    }
}
