// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class StartSubmissionUploadParams {
    protected jplagTutorial.jplagClient.Option submissionParams;
    protected int filesize;
    protected byte[] data;
    
    public StartSubmissionUploadParams() {
    }
    
    public StartSubmissionUploadParams(jplagTutorial.jplagClient.Option submissionParams, int filesize, byte[] data) {
        this.submissionParams = submissionParams;
        this.filesize = filesize;
        this.data = data;
    }
    
    public jplagTutorial.jplagClient.Option getSubmissionParams() {
        return submissionParams;
    }
    
    public void setSubmissionParams(jplagTutorial.jplagClient.Option submissionParams) {
        this.submissionParams = submissionParams;
    }
    
    public int getFilesize() {
        return filesize;
    }
    
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }
    
    public byte[] getData() {
        return data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }
}
