// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class Status {
    protected int state;
    protected int progress;
    protected java.lang.String report;
    
    public Status() {
    }
    
    public Status(int state, int progress, java.lang.String report) {
        this.state = state;
        this.progress = progress;
        this.report = report;
    }
    
    public int getState() {
        return state;
    }
    
    public void setState(int state) {
        this.state = state;
    }
    
    public int getProgress() {
        return progress;
    }
    
    public void setProgress(int progress) {
        this.progress = progress;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
}
