// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class UpdateUserInfoParams {
    protected java.lang.String newPassword;
    protected java.lang.String newEmailSecond;
    protected java.lang.String newHomepage;
    
    public UpdateUserInfoParams() {
    }
    
    public UpdateUserInfoParams(java.lang.String newPassword, java.lang.String newEmailSecond, java.lang.String newHomepage) {
        this.newPassword = newPassword;
        this.newEmailSecond = newEmailSecond;
        this.newHomepage = newHomepage;
    }
    
    public java.lang.String getNewPassword() {
        return newPassword;
    }
    
    public void setNewPassword(java.lang.String newPassword) {
        this.newPassword = newPassword;
    }
    
    public java.lang.String getNewEmailSecond() {
        return newEmailSecond;
    }
    
    public void setNewEmailSecond(java.lang.String newEmailSecond) {
        this.newEmailSecond = newEmailSecond;
    }
    
    public java.lang.String getNewHomepage() {
        return newHomepage;
    }
    
    public void setNewHomepage(java.lang.String newHomepage) {
        this.newHomepage = newHomepage;
    }
}
