// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class UserDataArray {
    protected jplagTutorial.jplagClient.UserData[] items;
    
    public UserDataArray() {
    }
    
    public UserDataArray(jplagTutorial.jplagClient.UserData[] items) {
        this.items = items;
    }
    
    public jplagTutorial.jplagClient.UserData[] getItems() {
        return items;
    }
    
    public void setItems(jplagTutorial.jplagClient.UserData[] items) {
        this.items = items;
    }
}
