// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class MailTemplate {
    protected java.lang.String name;
    protected java.lang.String subject;
    protected java.lang.String data;
    
    public MailTemplate() {
    }
    
    public MailTemplate(java.lang.String name, java.lang.String subject, java.lang.String data) {
        this.name = name;
        this.subject = subject;
        this.data = data;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getSubject() {
        return subject;
    }
    
    public void setSubject(java.lang.String subject) {
        this.subject = subject;
    }
    
    public java.lang.String getData() {
        return data;
    }
    
    public void setData(java.lang.String data) {
        this.data = data;
    }
}
