// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class NotifyDevelopersParams {
    protected java.lang.String subject;
    protected java.lang.String message;
    
    public NotifyDevelopersParams() {
    }
    
    public NotifyDevelopersParams(java.lang.String subject, java.lang.String message) {
        this.subject = subject;
        this.message = message;
    }
    
    public java.lang.String getSubject() {
        return subject;
    }
    
    public void setSubject(java.lang.String subject) {
        this.subject = subject;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
}
