// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class RequestDataArray_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_items_QNAME = new QName("", "items");
    private static final javax.xml.namespace.QName ns3_RequestData_TYPE_QNAME = new QName("http://www.ipd.uni-karlsruhe.de/jplag/types", "RequestData");
    private CombinedSerializer ns3_myRequestData_LiteralSerializer;
    
    public RequestDataArray_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public RequestDataArray_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns3_myRequestData_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", jplagTutorial.jplagClient.RequestData.class, ns3_RequestData_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        jplagTutorial.jplagClient.RequestDataArray instance = new jplagTutorial.jplagClient.RequestDataArray();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_items_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_items_QNAME))) {
                    value = ns3_myRequestData_LiteralSerializer.deserialize(ns1_items_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new jplagTutorial.jplagClient.RequestData[values.size()];
            member = values.toArray((Object[]) member);
            instance.setItems((jplagTutorial.jplagClient.RequestData[])member);
        }
        else {
            instance.setItems(new jplagTutorial.jplagClient.RequestData[0]);
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        jplagTutorial.jplagClient.RequestDataArray instance = (jplagTutorial.jplagClient.RequestDataArray)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        jplagTutorial.jplagClient.RequestDataArray instance = (jplagTutorial.jplagClient.RequestDataArray)obj;
        
        if (instance.getItems() != null) {
            for (int i = 0; i < instance.getItems().length; ++i) {
                ns3_myRequestData_LiteralSerializer.serialize(instance.getItems()[i], ns1_items_QNAME, null, writer, context);
            }
        }
    }
}
