// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class SetDeveloperStateParams {
    protected java.lang.String username;
    protected java.lang.String password;
    protected boolean developer;
    
    public SetDeveloperStateParams() {
    }
    
    public SetDeveloperStateParams(java.lang.String username, java.lang.String password, boolean developer) {
        this.username = username;
        this.password = password;
        this.developer = developer;
    }
    
    public java.lang.String getUsername() {
        return username;
    }
    
    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public boolean isDeveloper() {
        return developer;
    }
    
    public void setDeveloper(boolean developer) {
        this.developer = developer;
    }
}
