// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package jplagTutorial.jplagClient;


public class Submission {
    protected java.lang.String submissionID;
    protected java.lang.String title;
    protected java.lang.String date;
    protected int lastState;
    
    public Submission() {
    }
    
    public Submission(java.lang.String submissionID, java.lang.String title, java.lang.String date, int lastState) {
        this.submissionID = submissionID;
        this.title = title;
        this.date = date;
        this.lastState = lastState;
    }
    
    public java.lang.String getSubmissionID() {
        return submissionID;
    }
    
    public void setSubmissionID(java.lang.String submissionID) {
        this.submissionID = submissionID;
    }
    
    public java.lang.String getTitle() {
        return title;
    }
    
    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getDate() {
        return date;
    }
    
    public void setDate(java.lang.String date) {
        this.date = date;
    }
    
    public int getLastState() {
        return lastState;
    }
    
    public void setLastState(int lastState) {
        this.lastState = lastState;
    }
}
